/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AppMixins.h
 *
 * 
 */

#ifndef FASTREPORT_CLOUD_MODELS_AppMixins_H_
#define FASTREPORT_CLOUD_MODELS_AppMixins_H_

#include "CloudKludge.h"
#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace fastreport {
namespace cloud {
namespace models {


/// <summary>
/// 
/// </summary>
class  AppMixins
    : public ModelBase
{
public:
    AppMixins();
    virtual ~AppMixins();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AppMixins members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getHead() const;
    bool headIsSet() const;
    void unsethead();

    void setHead(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getBody() const;
    bool bodyIsSet() const;
    void unsetbody();

    void setBody(const utility::string_t& value);


protected:
    utility::string_t m_head;
    bool m_headIsSet;
    utility::string_t m_body;
    bool m_bodyIsSet;
};


}
}
}

#endif /* FASTREPORT_CLOUD_MODELS_AppMixins_H_ */
