/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CreateSubscriptionVM.h"

namespace fastreport {
namespace cloud {
namespace models {




CreateSubscriptionVM::CreateSubscriptionVM()
{
    m_planId = utility::conversions::to_string_t("");
    m_planIdIsSet = false;
    m_name = utility::conversions::to_string_t("");
    m_nameIsSet = false;
    m_userId = utility::conversions::to_string_t("");
    m_userIdIsSet = false;
}

CreateSubscriptionVM::~CreateSubscriptionVM()
{
}

void CreateSubscriptionVM::validate()
{
    // TODO: implement validation
}

web::json::value CreateSubscriptionVM::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_planIdIsSet)
    {
        val[utility::conversions::to_string_t("planId")] = ModelBase::toJson(m_planId);
    }
    if(m_nameIsSet)
    {
        val[utility::conversions::to_string_t("name")] = ModelBase::toJson(m_name);
    }
    if(m_userIdIsSet)
    {
        val[utility::conversions::to_string_t("userId")] = ModelBase::toJson(m_userId);
    }

    return val;
}

bool CreateSubscriptionVM::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("planId")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("planId"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_planId;
            ok &= ModelBase::fromJson(fieldValue, refVal_planId);
            setPlanId(refVal_planId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("name")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("name"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_name;
            ok &= ModelBase::fromJson(fieldValue, refVal_name);
            setName(refVal_name);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("userId")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("userId"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_userId;
            ok &= ModelBase::fromJson(fieldValue, refVal_userId);
            setUserId(refVal_userId);
        }
    }
    return ok;
}

void CreateSubscriptionVM::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_planIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("planId"), m_planId));
    }
    if(m_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("name"), m_name));
    }
    if(m_userIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("userId"), m_userId));
    }
}

bool CreateSubscriptionVM::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("planId")))
    {
        utility::string_t refVal_planId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("planId")), refVal_planId );
        setPlanId(refVal_planId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("name")))
    {
        utility::string_t refVal_name;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("name")), refVal_name );
        setName(refVal_name);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("userId")))
    {
        utility::string_t refVal_userId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("userId")), refVal_userId );
        setUserId(refVal_userId);
    }
    return ok;
}

utility::string_t CreateSubscriptionVM::getPlanId() const
{
    return m_planId;
}

void CreateSubscriptionVM::setPlanId(const utility::string_t& value)
{
    m_planId = value;
    m_planIdIsSet = true;
}

bool CreateSubscriptionVM::planIdIsSet() const
{
    return m_planIdIsSet;
}

void CreateSubscriptionVM::unsetplanId()
{
    m_planIdIsSet = false;
}
utility::string_t CreateSubscriptionVM::getName() const
{
    return m_name;
}

void CreateSubscriptionVM::setName(const utility::string_t& value)
{
    m_name = value;
    m_nameIsSet = true;
}

bool CreateSubscriptionVM::nameIsSet() const
{
    return m_nameIsSet;
}

void CreateSubscriptionVM::unsetname()
{
    m_nameIsSet = false;
}
utility::string_t CreateSubscriptionVM::getUserId() const
{
    return m_userId;
}

void CreateSubscriptionVM::setUserId(const utility::string_t& value)
{
    m_userId = value;
    m_userIdIsSet = true;
}

bool CreateSubscriptionVM::userIdIsSet() const
{
    return m_userIdIsSet;
}

void CreateSubscriptionVM::unsetuserId()
{
    m_userIdIsSet = false;
}
}
}
}


