/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * FrontendApp.h
 *
 * 
 */

#ifndef FASTREPORT_CLOUD_MODELS_FrontendApp_H_
#define FASTREPORT_CLOUD_MODELS_FrontendApp_H_

#include "CloudKludge.h"
#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "AppMixins.h"

namespace fastreport {
namespace cloud {
namespace models {


/// <summary>
/// 
/// </summary>
class  FrontendApp
    : public ModelBase
{
public:
    FrontendApp();
    virtual ~FrontendApp();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FrontendApp members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<AppMixins> getMixins() const;
    bool mixinsIsSet() const;
    void unsetmixins();

    void setMixins(const std::shared_ptr<AppMixins>& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getInvariantLocale() const;
    bool invariantLocaleIsSet() const;
    void unsetinvariantLocale();

    void setInvariantLocale(const utility::string_t& value);


protected:
    std::shared_ptr<AppMixins> m_mixins;
    bool m_mixinsIsSet;
    utility::string_t m_invariantLocale;
    bool m_invariantLocaleIsSet;
};


}
}
}

#endif /* FASTREPORT_CLOUD_MODELS_FrontendApp_H_ */
