/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "UpdateSubscriptionLocaleVM.h"

namespace fastreport {
namespace cloud {
namespace models {




UpdateSubscriptionLocaleVM::UpdateSubscriptionLocaleVM()
{
    m_locale = utility::conversions::to_string_t("");
    m_localeIsSet = false;
}

UpdateSubscriptionLocaleVM::~UpdateSubscriptionLocaleVM()
{
}

void UpdateSubscriptionLocaleVM::validate()
{
    // TODO: implement validation
}

web::json::value UpdateSubscriptionLocaleVM::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_localeIsSet)
    {
        val[utility::conversions::to_string_t("locale")] = ModelBase::toJson(m_locale);
    }

    return val;
}

bool UpdateSubscriptionLocaleVM::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("locale")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("locale"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_locale;
            ok &= ModelBase::fromJson(fieldValue, refVal_locale);
            setLocale(refVal_locale);
        }
    }
    return ok;
}

void UpdateSubscriptionLocaleVM::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_localeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("locale"), m_locale));
    }
}

bool UpdateSubscriptionLocaleVM::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("locale")))
    {
        utility::string_t refVal_locale;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("locale")), refVal_locale );
        setLocale(refVal_locale);
    }
    return ok;
}

utility::string_t UpdateSubscriptionLocaleVM::getLocale() const
{
    return m_locale;
}

void UpdateSubscriptionLocaleVM::setLocale(const utility::string_t& value)
{
    m_locale = value;
    m_localeIsSet = true;
}

bool UpdateSubscriptionLocaleVM::localeIsSet() const
{
    return m_localeIsSet;
}

void UpdateSubscriptionLocaleVM::unsetlocale()
{
    m_localeIsSet = false;
}
}
}
}


