/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AnalysisResultVM.h
 *
 * 
 */

#ifndef FASTREPORT_CLOUD_MODELS_AnalysisResultVM_H_
#define FASTREPORT_CLOUD_MODELS_AnalysisResultVM_H_


#include "CppRestOpenAPIClient/model/ProblemLevel.h"
#include "CppRestOpenAPIClient/model/ProblemType.h"
#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/CloudBaseVM.h"

namespace fastreport {
namespace cloud {
namespace models {


/// <summary>
/// 
/// </summary>
class  AnalysisResultVM
    : public CloudBaseVM
{
public:
    AnalysisResultVM();
    virtual ~AnalysisResultVM();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AnalysisResultVM members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ProblemLevel> getLevel() const;
    bool levelIsSet() const;
    void unsetlevel();

    void setLevel(const std::shared_ptr<ProblemLevel>& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDetail() const;
    bool detailIsSet() const;
    void unsetdetail();

    void setDetail(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetid();

    void setId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSubscriptionId() const;
    bool subscriptionIdIsSet() const;
    void unsetsubscriptionId();

    void setSubscriptionId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getFileId() const;
    bool fileIdIsSet() const;
    void unsetfileId();

    void setFileId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getCollectionName() const;
    bool collectionNameIsSet() const;
    void unsetcollectionName();

    void setCollectionName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ProblemType> getType() const;
    bool typeIsSet() const;
    void unsettype();

    void setType(const std::shared_ptr<ProblemType>& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSignature() const;
    bool signatureIsSet() const;
    void unsetsignature();

    void setSignature(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    int64_t getNewSize() const;
    bool newSizeIsSet() const;
    void unsetnewSize();

    void setNewSize(int64_t value);


protected:
    std::shared_ptr<ProblemLevel> m_level;
    bool m_levelIsSet;
    utility::string_t m_detail;
    bool m_detailIsSet;
    utility::string_t m_id;
    bool m_idIsSet;
    utility::string_t m_subscriptionId;
    bool m_subscriptionIdIsSet;
    utility::string_t m_fileId;
    bool m_fileIdIsSet;
    utility::string_t m_collectionName;
    bool m_collectionNameIsSet;
    std::shared_ptr<ProblemType> m_type;
    bool m_typeIsSet;
    utility::string_t m_signature;
    bool m_signatureIsSet;
    int64_t m_newSize;
    bool m_newSizeIsSet;
};


}
}
}

#endif /* FASTREPORT_CLOUD_MODELS_AnalysisResultVM_H_ */
