/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CheckUserByPasswordInternalVM.h
 *
 * 
 */

#ifndef FASTREPORT_CLOUD_MODELS_CheckUserByPasswordInternalVM_H_
#define FASTREPORT_CLOUD_MODELS_CheckUserByPasswordInternalVM_H_


#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/CloudBaseVM.h"

namespace fastreport {
namespace cloud {
namespace models {


/// <summary>
/// 
/// </summary>
class  CheckUserByPasswordInternalVM
    : public CloudBaseVM
{
public:
    CheckUserByPasswordInternalVM();
    virtual ~CheckUserByPasswordInternalVM();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CheckUserByPasswordInternalVM members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getEmail() const;
    bool emailIsSet() const;
    void unsetemail();

    void setEmail(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getPassword() const;
    bool passwordIsSet() const;
    void unsetpassword();

    void setPassword(const utility::string_t& value);


protected:
    utility::string_t m_email;
    bool m_emailIsSet;
    utility::string_t m_password;
    bool m_passwordIsSet;
};


}
}
}

#endif /* FASTREPORT_CLOUD_MODELS_CheckUserByPasswordInternalVM_H_ */
