/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CreateSubscriptionVM.h
 *
 * 
 */

#ifndef FASTREPORT_CLOUD_MODELS_CreateSubscriptionVM_H_
#define FASTREPORT_CLOUD_MODELS_CreateSubscriptionVM_H_


#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/CloudBaseVM.h"
#include <vector>

namespace fastreport {
namespace cloud {
namespace models {


/// <summary>
/// 
/// </summary>
class  CreateSubscriptionVM
    : public CloudBaseVM
{
public:
    CreateSubscriptionVM();
    virtual ~CreateSubscriptionVM();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CreateSubscriptionVM members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getPlanId() const;
    bool planIdIsSet() const;
    void unsetplanId();

    void setPlanId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getStart() const;
    bool startIsSet() const;
    void unsetstart();

    void setStart(const utility::datetime& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getEnd() const;
    bool endIsSet() const;
    void unsetend();

    void setEnd(const utility::datetime& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetname();

    void setName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUserId() const;
    bool userIdIsSet() const;
    void unsetuserId();

    void setUserId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getTags();
    bool tagsIsSet() const;
    void unsettags();

    void setTags(const std::vector<utility::string_t>& value);


protected:
    utility::string_t m_planId;
    bool m_planIdIsSet;
    utility::datetime m_start;
    bool m_startIsSet;
    utility::datetime m_end;
    bool m_endIsSet;
    utility::string_t m_name;
    bool m_nameIsSet;
    utility::string_t m_userId;
    bool m_userIdIsSet;
    std::vector<utility::string_t> m_tags;
    bool m_tagsIsSet;
};


}
}
}

#endif /* FASTREPORT_CLOUD_MODELS_CreateSubscriptionVM_H_ */
