/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DataSourceSelectCommandParameterVM.h
 *
 * 
 */

#ifndef FASTREPORT_CLOUD_MODELS_DataSourceSelectCommandParameterVM_H_
#define FASTREPORT_CLOUD_MODELS_DataSourceSelectCommandParameterVM_H_


#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/CloudBaseVM.h"

namespace fastreport {
namespace cloud {
namespace models {


/// <summary>
/// 
/// </summary>
class  DataSourceSelectCommandParameterVM
    : public CloudBaseVM
{
public:
    DataSourceSelectCommandParameterVM();
    virtual ~DataSourceSelectCommandParameterVM();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DataSourceSelectCommandParameterVM members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetname();

    void setName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDataType() const;
    bool dataTypeIsSet() const;
    void unsetdataType();

    void setDataType(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDefaultValue() const;
    bool defaultValueIsSet() const;
    void unsetdefaultValue();

    void setDefaultValue(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getSize() const;
    bool sizeIsSet() const;
    void unsetsize();

    void setSize(int32_t value);


protected:
    utility::string_t m_name;
    bool m_nameIsSet;
    utility::string_t m_dataType;
    bool m_dataTypeIsSet;
    utility::string_t m_defaultValue;
    bool m_defaultValueIsSet;
    int32_t m_size;
    bool m_sizeIsSet;
};


}
}
}

#endif /* FASTREPORT_CLOUD_MODELS_DataSourceSelectCommandParameterVM_H_ */
