/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DataSourcePermissionsCRUDVM.h
 *
 * 
 */

#ifndef FASTREPORT_CLOUD_MODELS_DataSourcePermissionsCRUDVM_H_
#define FASTREPORT_CLOUD_MODELS_DataSourcePermissionsCRUDVM_H_


#include "CppRestOpenAPIClient/model/DataSourcePermissionCRUDVM.h"
#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/CloudBaseVM.h"
#include <map>

namespace fastreport {
namespace cloud {
namespace models {

class DataSourcePermissionCRUDVM;

/// <summary>
/// 
/// </summary>
class  DataSourcePermissionsCRUDVM
    : public CloudBaseVM
{
public:
    DataSourcePermissionsCRUDVM();
    virtual ~DataSourcePermissionsCRUDVM();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DataSourcePermissionsCRUDVM members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getOwnerId() const;
    bool ownerIdIsSet() const;
    void unsetownerId();

    void setOwnerId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<DataSourcePermissionCRUDVM> getOwner() const;
    bool ownerIsSet() const;
    void unsetowner();

    void setOwner(const std::shared_ptr<DataSourcePermissionCRUDVM>& value);

    /// <summary>
    /// 
    /// </summary>
    std::map<utility::string_t, std::shared_ptr<DataSourcePermissionCRUDVM>>& getGroups();
    bool groupsIsSet() const;
    void unsetgroups();

    void setGroups(const std::map<utility::string_t, std::shared_ptr<DataSourcePermissionCRUDVM>>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<DataSourcePermissionCRUDVM> getOther() const;
    bool otherIsSet() const;
    void unsetother();

    void setOther(const std::shared_ptr<DataSourcePermissionCRUDVM>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<DataSourcePermissionCRUDVM> getAnon() const;
    bool anonIsSet() const;
    void unsetanon();

    void setAnon(const std::shared_ptr<DataSourcePermissionCRUDVM>& value);


protected:
    utility::string_t m_ownerId;
    bool m_ownerIdIsSet;
    std::shared_ptr<DataSourcePermissionCRUDVM> m_owner;
    bool m_ownerIsSet;
    std::map<utility::string_t, std::shared_ptr<DataSourcePermissionCRUDVM>> m_groups;
    bool m_groupsIsSet;
    std::shared_ptr<DataSourcePermissionCRUDVM> m_other;
    bool m_otherIsSet;
    std::shared_ptr<DataSourcePermissionCRUDVM> m_anon;
    bool m_anonIsSet;
};


}
}
}

#endif /* FASTREPORT_CLOUD_MODELS_DataSourcePermissionsCRUDVM_H_ */
