/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RestOfSpaceVM.h
 *
 * 
 */

#ifndef FASTREPORT_CLOUD_MODELS_RestOfSpaceVM_H_
#define FASTREPORT_CLOUD_MODELS_RestOfSpaceVM_H_


#include "CppRestOpenAPIClient/model/SubscriptionPlanVM.h"
#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/CloudBaseVM.h"

namespace fastreport {
namespace cloud {
namespace models {

class SubscriptionPlanVM;

/// <summary>
/// 
/// </summary>
class  RestOfSpaceVM
    : public CloudBaseVM
{
public:
    RestOfSpaceVM();
    virtual ~RestOfSpaceVM();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// RestOfSpaceVM members

    /// <summary>
    /// 
    /// </summary>
    int64_t getRestOfSpace() const;
    bool restOfSpaceIsSet() const;
    void unsetrestOfSpace();

    void setRestOfSpace(int64_t value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<SubscriptionPlanVM> getSubscriptionPlan() const;
    bool subscriptionPlanIsSet() const;
    void unsetsubscriptionPlan();

    void setSubscriptionPlan(const std::shared_ptr<SubscriptionPlanVM>& value);


protected:
    int64_t m_restOfSpace;
    bool m_restOfSpaceIsSet;
    std::shared_ptr<SubscriptionPlanVM> m_subscriptionPlan;
    bool m_subscriptionPlanIsSet;
};


}
}
}

#endif /* FASTREPORT_CLOUD_MODELS_RestOfSpaceVM_H_ */
