/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TaskPermission.h
 *
 * 
 */

#ifndef FASTREPORT_CLOUD_MODELS_TaskPermission_H_
#define FASTREPORT_CLOUD_MODELS_TaskPermission_H_

#include "CloudKludge.h"
#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/TaskGet.h"
#include "CppRestOpenAPIClient/model/TaskCreateTaskGetTaskUpdateTaskDeleteTaskExecuteTaskAdministratePermission.h"
#include "CppRestOpenAPIClient/model/TaskExecute.h"
#include "CppRestOpenAPIClient/model/TaskDelete.h"
#include "CppRestOpenAPIClient/model/TaskAdministrate.h"
#include "CppRestOpenAPIClient/model/TaskUpdate.h"
#include "CppRestOpenAPIClient/model/TaskCreate.h"

namespace fastreport {
namespace cloud {
namespace models {


/// <summary>
/// 
/// </summary>
class  TaskPermission
    : public ModelBase
{
public:
    TaskPermission();
    virtual ~TaskPermission();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// TaskPermission members


protected:
};


}
}
}

#endif /* FASTREPORT_CLOUD_MODELS_TaskPermission_H_ */
