/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TaskPermissionsVM.h
 *
 * 
 */

#ifndef FASTREPORT_CLOUD_MODELS_TaskPermissionsVM_H_
#define FASTREPORT_CLOUD_MODELS_TaskPermissionsVM_H_


#include "CppRestOpenAPIClient/model/TaskPermissionsCRUDVM.h"
#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/CloudBaseVM.h"

namespace fastreport {
namespace cloud {
namespace models {

class TaskPermissionsCRUDVM;

/// <summary>
/// 
/// </summary>
class  TaskPermissionsVM
    : public CloudBaseVM
{
public:
    TaskPermissionsVM();
    virtual ~TaskPermissionsVM();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// TaskPermissionsVM members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<TaskPermissionsCRUDVM> getPermissions() const;
    bool permissionsIsSet() const;
    void unsetpermissions();

    void setPermissions(const std::shared_ptr<TaskPermissionsCRUDVM>& value);


protected:
    std::shared_ptr<TaskPermissionsCRUDVM> m_permissions;
    bool m_permissionsIsSet;
};


}
}
}

#endif /* FASTREPORT_CLOUD_MODELS_TaskPermissionsVM_H_ */
