/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UpdatePrepareTemplateTaskVM.h
 *
 * 
 */

#ifndef FASTREPORT_CLOUD_MODELS_UpdatePrepareTemplateTaskVM_H_
#define FASTREPORT_CLOUD_MODELS_UpdatePrepareTemplateTaskVM_H_

#include "CloudKludge.h"
#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/UpdateTransformTaskBaseVM.h"
#include <map>
#include <vector>

namespace fastreport {
namespace cloud {
namespace models {


/// <summary>
/// 
/// </summary>
class  UpdatePrepareTemplateTaskVM
    : public ModelBase
{
public:
    UpdatePrepareTemplateTaskVM();
    virtual ~UpdatePrepareTemplateTaskVM();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UpdatePrepareTemplateTaskVM members

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getExportIds();
    bool exportIdsIsSet() const;
    void unsetexportIds();

    void setExportIds(const std::vector<utility::string_t>& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getPagesCount() const;
    bool pagesCountIsSet() const;
    void unsetpagesCount();

    void setPagesCount(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::map<utility::string_t, utility::string_t>& getReportParameters();
    bool reportParametersIsSet() const;
    void unsetreportParameters();

    void setReportParameters(const std::map<utility::string_t, utility::string_t>& value);


protected:
    std::vector<utility::string_t> m_exportIds;
    bool m_exportIdsIsSet;
    int32_t m_pagesCount;
    bool m_pagesCountIsSet;
    std::map<utility::string_t, utility::string_t> m_reportParameters;
    bool m_reportParametersIsSet;
};


}
}
}

#endif /* FASTREPORT_CLOUD_MODELS_UpdatePrepareTemplateTaskVM_H_ */
