/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/AdminSubscriptionsVM.h"

namespace fastreport {
namespace cloud {
namespace models {



AdminSubscriptionsVM::AdminSubscriptionsVM()
{
    m_subscriptionsIsSet = false;
    m_count = 0L;
    m_countIsSet = false;
    m_skip = 0;
    m_skipIsSet = false;
    m_take = 0;
    m_takeIsSet = false;
}

AdminSubscriptionsVM::~AdminSubscriptionsVM()
{
}

void AdminSubscriptionsVM::validate()
{
    // TODO: implement validation
}

web::json::value AdminSubscriptionsVM::toJson() const
{
    web::json::value val = this->CloudBaseVM::toJson();
    
    if(m_subscriptionsIsSet)
    {
        val[utility::conversions::to_string_t(U("subscriptions"))] = ModelBase::toJson(m_subscriptions);
    }
    if(m_countIsSet)
    {
        val[utility::conversions::to_string_t(U("count"))] = ModelBase::toJson(m_count);
    }
    if(m_skipIsSet)
    {
        val[utility::conversions::to_string_t(U("skip"))] = ModelBase::toJson(m_skip);
    }
    if(m_takeIsSet)
    {
        val[utility::conversions::to_string_t(U("take"))] = ModelBase::toJson(m_take);
    }

    return val;
}

bool AdminSubscriptionsVM::fromJson(const web::json::value& val)
{
    bool ok = true;
    ok &= this->CloudBaseVM::fromJson(val);
    
    if(val.has_field(utility::conversions::to_string_t(U("subscriptions"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("subscriptions")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<AdminSubscriptionVM>> refVal_setSubscriptions;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubscriptions);
            setSubscriptions(refVal_setSubscriptions);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("count")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCount);
            setCount(refVal_setCount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("skip"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("skip")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setSkip;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSkip);
            setSkip(refVal_setSkip);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("take"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("take")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTake;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTake);
            setTake(refVal_setTake);
        }
    }
    return ok;
}

void AdminSubscriptionsVM::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_subscriptionsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("subscriptions")), m_subscriptions));
    }
    if(m_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("count")), m_count));
    }
    if(m_skipIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("skip")), m_skip));
    }
    if(m_takeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("take")), m_take));
    }
    if(m_tIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("$t")), m_t));
    }
}

bool AdminSubscriptionsVM::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("subscriptions"))))
    {
        std::vector<std::shared_ptr<AdminSubscriptionVM>> refVal_setSubscriptions;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("subscriptions"))), refVal_setSubscriptions );
        setSubscriptions(refVal_setSubscriptions);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("count"))))
    {
        int64_t refVal_setCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("count"))), refVal_setCount );
        setCount(refVal_setCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("skip"))))
    {
        int32_t refVal_setSkip;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("skip"))), refVal_setSkip );
        setSkip(refVal_setSkip);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("take"))))
    {
        int32_t refVal_setTake;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("take"))), refVal_setTake );
        setTake(refVal_setTake);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("$t"))))
    {
        utility::string_t refVal_setT;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("$t"))), refVal_setT );
        setT(refVal_setT);
    }
    return ok;
}

std::vector<std::shared_ptr<AdminSubscriptionVM>>& AdminSubscriptionsVM::getSubscriptions()
{
    return m_subscriptions;
}

void AdminSubscriptionsVM::setSubscriptions(const std::vector<std::shared_ptr<AdminSubscriptionVM>>& value)
{
    m_subscriptions = value;
    m_subscriptionsIsSet = true;
}

bool AdminSubscriptionsVM::subscriptionsIsSet() const
{
    return m_subscriptionsIsSet;
}

void AdminSubscriptionsVM::unsetsubscriptions()
{
    m_subscriptionsIsSet = false;
}
int64_t AdminSubscriptionsVM::getCount() const
{
    return m_count;
}

void AdminSubscriptionsVM::setCount(int64_t value)
{
    m_count = value;
    m_countIsSet = true;
}

bool AdminSubscriptionsVM::countIsSet() const
{
    return m_countIsSet;
}

void AdminSubscriptionsVM::unsetcount()
{
    m_countIsSet = false;
}
int32_t AdminSubscriptionsVM::getSkip() const
{
    return m_skip;
}

void AdminSubscriptionsVM::setSkip(int32_t value)
{
    m_skip = value;
    m_skipIsSet = true;
}

bool AdminSubscriptionsVM::skipIsSet() const
{
    return m_skipIsSet;
}

void AdminSubscriptionsVM::unsetskip()
{
    m_skipIsSet = false;
}
int32_t AdminSubscriptionsVM::getTake() const
{
    return m_take;
}

void AdminSubscriptionsVM::setTake(int32_t value)
{
    m_take = value;
    m_takeIsSet = true;
}

bool AdminSubscriptionsVM::takeIsSet() const
{
    return m_takeIsSet;
}

void AdminSubscriptionsVM::unsettake()
{
    m_takeIsSet = false;
}
}
}
}


