/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/AdminUpdate.h"

namespace fastreport {
namespace cloud {
namespace models {


namespace
{
using EnumUnderlyingType = int64_t;

AdminUpdate::eAdminUpdate toEnum(const EnumUnderlyingType& val)
{
    switch (val)
    {
    case 0:
        return AdminUpdate::eAdminUpdate::AdminUpdate__0;
    case 1:
        return AdminUpdate::eAdminUpdate::AdminUpdate__1;
    case 2:
        return AdminUpdate::eAdminUpdate::AdminUpdate__2;
    case 4:
        return AdminUpdate::eAdminUpdate::AdminUpdate__4;
    case 8:
        return AdminUpdate::eAdminUpdate::AdminUpdate__8;
    case 16:
        return AdminUpdate::eAdminUpdate::AdminUpdate__16;
    case 32:
        return AdminUpdate::eAdminUpdate::AdminUpdate__32;
    case -1:
        return AdminUpdate::eAdminUpdate::AdminUpdate__12;
    default:
        break;
    }
    return {};
}

EnumUnderlyingType fromEnum(AdminUpdate::eAdminUpdate e)
{
    switch (e)
    {
    case AdminUpdate::eAdminUpdate::AdminUpdate__0:
        return 0;
    case AdminUpdate::eAdminUpdate::AdminUpdate__1:
        return 1;
    case AdminUpdate::eAdminUpdate::AdminUpdate__2:
        return 2;
    case AdminUpdate::eAdminUpdate::AdminUpdate__4:
        return 4;
    case AdminUpdate::eAdminUpdate::AdminUpdate__8:
        return 8;
    case AdminUpdate::eAdminUpdate::AdminUpdate__16:
        return 16;
    case AdminUpdate::eAdminUpdate::AdminUpdate__32:
        return 32;
    case AdminUpdate::eAdminUpdate::AdminUpdate__12:
        return -1;
    default:
        break;
    }
    return {};
}
}

AdminUpdate::AdminUpdate()
{
}

AdminUpdate::~AdminUpdate()
{
}

void AdminUpdate::validate()
{
    // TODO: implement validation
}

web::json::value AdminUpdate::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool AdminUpdate::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_number().to_int64());
    return true;
}

void AdminUpdate::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool AdminUpdate::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

AdminUpdate::eAdminUpdate AdminUpdate::getValue() const
{
   return m_value;
}

void AdminUpdate::setValue(AdminUpdate::eAdminUpdate const value)
{
   m_value = value;
}


}
}
}


