/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.3.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/BreadcrumbsVM.h"

namespace fastreport {
namespace cloud {
namespace models {



BreadcrumbsVM::BreadcrumbsVM()
{
    m_breadcrumbsIsSet = false;
}

BreadcrumbsVM::~BreadcrumbsVM()
{
}

void BreadcrumbsVM::validate()
{
    // TODO: implement validation
}

web::json::value BreadcrumbsVM::toJson() const
{
    web::json::value val = this->CloudBaseVM::toJson();
    
    if(m_breadcrumbsIsSet)
    {
        val[utility::conversions::to_string_t(U("breadcrumbs"))] = ModelBase::toJson(m_breadcrumbs);
    }

    return val;
}

bool BreadcrumbsVM::fromJson(const web::json::value& val)
{
    bool ok = true;
    ok &= this->CloudBaseVM::fromJson(val);
    
    if(val.has_field(utility::conversions::to_string_t(U("breadcrumbs"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("breadcrumbs")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<BreadcrumbsModel>> refVal_setBreadcrumbs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBreadcrumbs);
            setBreadcrumbs(refVal_setBreadcrumbs);
        }
    }
    return ok;
}

void BreadcrumbsVM::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_breadcrumbsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("breadcrumbs")), m_breadcrumbs));
    }
    if(m_tIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("$t")), m_t));
    }
}

bool BreadcrumbsVM::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("breadcrumbs"))))
    {
        std::vector<std::shared_ptr<BreadcrumbsModel>> refVal_setBreadcrumbs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("breadcrumbs"))), refVal_setBreadcrumbs );
        setBreadcrumbs(refVal_setBreadcrumbs);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("$t"))))
    {
        utility::string_t refVal_setT;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("$t"))), refVal_setT );
        setT(refVal_setT);
    }
    return ok;
}

std::vector<std::shared_ptr<BreadcrumbsModel>>& BreadcrumbsVM::getBreadcrumbs()
{
    return m_breadcrumbs;
}

void BreadcrumbsVM::setBreadcrumbs(const std::vector<std::shared_ptr<BreadcrumbsModel>>& value)
{
    m_breadcrumbs = value;
    m_breadcrumbsIsSet = true;
}

bool BreadcrumbsVM::breadcrumbsIsSet() const
{
    return m_breadcrumbsIsSet;
}

void BreadcrumbsVM::unsetbreadcrumbs()
{
    m_breadcrumbsIsSet = false;
}
}
}
}


