/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/DataSourceExecute.h"

namespace fastreport {
namespace cloud {
namespace models {


namespace
{
using EnumUnderlyingType = int64_t;

DataSourceExecute::eDataSourceExecute toEnum(const EnumUnderlyingType& val)
{
    switch (val)
    {
    case 0:
        return DataSourceExecute::eDataSourceExecute::DataSourceExecute__0;
    case -1:
        return DataSourceExecute::eDataSourceExecute::DataSourceExecute__1;
    default:
        break;
    }
    return {};
}

EnumUnderlyingType fromEnum(DataSourceExecute::eDataSourceExecute e)
{
    switch (e)
    {
    case DataSourceExecute::eDataSourceExecute::DataSourceExecute__0:
        return 0;
    case DataSourceExecute::eDataSourceExecute::DataSourceExecute__1:
        return -1;
    default:
        break;
    }
    return {};
}
}

DataSourceExecute::DataSourceExecute()
{
}

DataSourceExecute::~DataSourceExecute()
{
}

void DataSourceExecute::validate()
{
    // TODO: implement validation
}

web::json::value DataSourceExecute::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool DataSourceExecute::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_number().to_int64());
    return true;
}

void DataSourceExecute::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool DataSourceExecute::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

DataSourceExecute::eDataSourceExecute DataSourceExecute::getValue() const
{
   return m_value;
}

void DataSourceExecute::setValue(DataSourceExecute::eDataSourceExecute const value)
{
   m_value = value;
}


}
}
}


