/**
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/SubscriptionCreate.h"

namespace fastreport {
namespace cloud {
namespace models {


namespace
{
using EnumUnderlyingType = int64_t;

SubscriptionCreate::eSubscriptionCreate toEnum(const EnumUnderlyingType& val)
{
    switch (val)
    {
    case 0:
        return SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__0;
    case 1:
        return SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__1;
    case 2:
        return SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__2;
    case 4:
        return SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__4;
    case 8:
        return SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__8;
    case 16:
        return SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__16;
    case 32:
        return SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__32;
    case 64:
        return SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__64;
    case -1:
        return SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__1;
    default:
        break;
    }
    return {};
}

EnumUnderlyingType fromEnum(SubscriptionCreate::eSubscriptionCreate e)
{
    switch (e)
    {
    case SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__0:
        return 0;
    case SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__1:
        return 1;
    case SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__2:
        return 2;
    case SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__4:
        return 4;
    case SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__8:
        return 8;
    case SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__16:
        return 16;
    case SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__32:
        return 32;
    case SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__64:
        return 64;
    case SubscriptionCreate::eSubscriptionCreate::SubscriptionCreate__1:
        return -1;
    default:
        break;
    }
    return {};
}
}

SubscriptionCreate::SubscriptionCreate()
{
}

SubscriptionCreate::~SubscriptionCreate()
{
}

void SubscriptionCreate::validate()
{
    // TODO: implement validation
}

web::json::value SubscriptionCreate::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool SubscriptionCreate::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_number().to_int64());
    return true;
}

void SubscriptionCreate::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool SubscriptionCreate::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

SubscriptionCreate::eSubscriptionCreate SubscriptionCreate::getValue() const
{
   return m_value;
}

void SubscriptionCreate::setValue(SubscriptionCreate::eSubscriptionCreate const value)
{
   m_value = value;
}


}
}
}


